//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemMngmt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_appointment
    {
        public byte[] Book_ID { get; set; }
        public string Session { get; set; }
        public int Order_number { get; set; }
        public System.DateTime Appointment_date { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
    }
}
