//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemMngmt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class book_appointment
    {
        public string book_id { get; set; }
        public string session { get; set; }
        public int order_number { get; set; }
        public System.DateTime appointment_date { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
    }
}
