//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemMngmt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnostic
    {
        public Diagnostic()
        {
            this.Prescribings = new HashSet<Prescribing>();
            this.Diseases = new HashSet<Disease>();
        }
    
        public string Diagnostic_ID { get; set; }
        public string Patient_ID { get; set; }
        public string Disease_ID { get; set; }
        public string Note { get; set; }
        public string Level { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual ICollection<Prescribing> Prescribings { get; set; }
        public virtual ICollection<Disease> Diseases { get; set; }
    }
}
