//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemMngmt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class diagnostic
    {
        public diagnostic()
        {
            this.prescribings = new HashSet<prescribing>();
            this.diseases = new HashSet<disease>();
        }
    
        public string diagnostic_id { get; set; }
        public string patient_id { get; set; }
        public string disease_id { get; set; }
        public System.DateTime date { get; set; }
        public string note { get; set; }
    
        public virtual patient patient { get; set; }
        public virtual ICollection<prescribing> prescribings { get; set; }
        public virtual ICollection<disease> diseases { get; set; }
    }
}
