//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemMngmt.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Disease
    {
        public Disease()
        {
            this.Diagnostics = new HashSet<Diagnostic>();
        }
        [Display(Name = "Mã bệnh")]
        [Required(ErrorMessage = "Vui lòng nhập mã bệnh")]
        public string Disease_ID { get; set; }
        [Display(Name="Tên bệnh")]
        [Required(ErrorMessage = "Vui lòng nhập tên bệnh")]
        public string Name { get; set; }
        [Display(Name = "Ghi chú")]
        public string Note { get; set; }
    
        public virtual ICollection<Diagnostic> Diagnostics { get; set; }
    }
}
