//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemMngmt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class disease
    {
        public disease()
        {
            this.diagnostics = new HashSet<diagnostic>();
        }
    
        public string disease_id { get; set; }
        public string name { get; set; }
        public string note { get; set; }
    
        public virtual ICollection<diagnostic> diagnostics { get; set; }
    }
}
