//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemMngmt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        public Medicine()
        {
            this.Medicine_Detail = new HashSet<Medicine_Detail>();
        }
    
        public string Medicine_ID { get; set; }
        public string Name { get; set; }
        public int Amount { get; set; }
        public long Price { get; set; }
        public string Types { get; set; }
        public System.DateTime Input_date { get; set; }
        public string Original_medicine { get; set; }
        public System.DateTime Expiration_Date { get; set; }
    
        public virtual ICollection<Medicine_Detail> Medicine_Detail { get; set; }
    }
}
