//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemMngmt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine_detail
    {
        public string medicine_id { get; set; }
        public string prescribing_id { get; set; }
        public string dosage { get; set; }
        public int amount { get; set; }
        public long price { get; set; }
        public string note { get; set; }
    
        public virtual Medicine Medicine { get; set; }
        public virtual Prescribing Prescribing { get; set; }
    }
}
