//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemMngmt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine_Detail
    {
        public string Prescribing_ID { get; set; }
        public string Medicine_ID { get; set; }
        public string Dosage { get; set; }
        public int Amount { get; set; }
        public long Price { get; set; }
        public string Note { get; set; }
    
        public virtual Medicine Medicine { get; set; }
        public virtual Prescribing Prescribing { get; set; }
    }
}
