//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemMngmt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        public Medicine()
        {
            this.Medicine_detail = new HashSet<Medicine_detail>();
        }
    
        public string medicine_id { get; set; }
        public string name { get; set; }
        public int amount { get; set; }
        public long price_per_unit { get; set; }
        public string type { get; set; }
        public System.DateTime input_date { get; set; }
        public string original_medicine { get; set; }
        public System.DateTime expiration_date { get; set; }
    
        public virtual ICollection<Medicine_detail> Medicine_detail { get; set; }
    }
}
