//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemMngmt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public string UserName { get; set; }
        public string Member_Name { get; set; }
        public string Member_Phone { get; set; }
        public string Passoword { get; set; }
        public string Member_Email { get; set; }
        public string Member_Role { get; set; }
    }
}
