//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemMngmt.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TheClinicEntities : DbContext
    {
        public TheClinicEntities()
            : base("name=TheClinicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<book_appointment> book_appointment { get; set; }
        public DbSet<diagnostic> diagnostics { get; set; }
        public DbSet<disease> diseases { get; set; }
        public DbSet<medicine> medicines { get; set; }
        public DbSet<patient> patients { get; set; }
        public DbSet<prescribing> prescribings { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<timework> timeworks { get; set; }
        public DbSet<user_info> user_info { get; set; }
        public DbSet<medicine_detail> medicine_detail { get; set; }
    }
}
