//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemMngmt.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DrNguyenClinicEntities : DbContext
    {
        public DrNguyenClinicEntities()
            : base("name=DrNguyenClinicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Book_appointment> Book_appointments { get; set; }
        public DbSet<Diagnostic> Diagnostics { get; set; }
        public DbSet<Disease> Diseases { get; set; }
        public DbSet<Medicine> Medicines { get; set; }
        public DbSet<Medicine_Detail> Medicine_Detail { get; set; }
        public DbSet<Member> Members { get; set; }
        public DbSet<Patient> Patients { get; set; }
        public DbSet<Prescribing> Prescribings { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TimeWork> TimeWorks { get; set; }
    }
}
