//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemMngmt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescribing
    {
        public Prescribing()
        {
            this.Medicine_detail = new HashSet<Medicine_detail>();
        }
    
        public string prescribing_id { get; set; }
        public string diagnostic_id { get; set; }
        public long examination_fee { get; set; }
        public System.DateTime date { get; set; }
        public string status { get; set; }
    
        public virtual Diagnostic Diagnostic { get; set; }
        public virtual ICollection<Medicine_detail> Medicine_detail { get; set; }
    }
}
