//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemMngmt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prescribing
    {
        public prescribing()
        {
            this.medicine_detail = new HashSet<medicine_detail>();
        }
    
        public string prescribing_id { get; set; }
        public string diagnostic_id { get; set; }
        public System.DateTime date { get; set; }
        public long examination_fee { get; set; }
        public int status { get; set; }
    
        public virtual diagnostic diagnostic { get; set; }
        public virtual ICollection<medicine_detail> medicine_detail { get; set; }
    }
}
