//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemMngmt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescribing
    {
        public string Prescribing_ID { get; set; }
        public string Diagnostic_ID { get; set; }
        public System.DateTime Date { get; set; }
        public string Status { get; set; }
        public long Examination_fee { get; set; }
    
        public virtual Diagnostic Diagnostic { get; set; }
        public virtual Medicine_Detail Medicine_Detail { get; set; }
    }
}
