//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemMngmt.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TimeWork
    {
        [Display(Name="Buổi")]
        [Required(ErrorMessage="Vui lòng nhập buổi")]
       
        public string Session { get; set; }
        [Display(Name = "Bắt đầu")]
        [Required(ErrorMessage = "Vui lòng nhập giờ bắt đầu")]
        [DataType(DataType.Time)]
        public System.TimeSpan Begin_time { get; set; }
        [Display(Name = "Kết thúc")]
        [Required(ErrorMessage = "Vui lòng nhập giờ kết thúc")]
        [DataType(DataType.Time)]
        public System.TimeSpan End_time { get; set; }
    }
}
